services:
  postgre:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: task_manager
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgre:/var/lib/postgresql/data
    networks:
      - tasks

  liquibase-migrations:
    image: liquibase/liquibase:4.25
    depends_on:
      - postgre
    command:
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgre:5432/task_manager
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - ./migrations:/liquibase/changelog
    networks:
      - tasks

volumes:
  postgre: { }

networks:
  tasks: { }