name: TaskManager CI

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}  # Personal Access Token for GitHub

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub Username
          password: ${{ secrets.DOCKER_TOKEN }}     # Docker Hub Access Token

      - name: Build Docker image with BuildKit caching
        run: |
          export DOCKER_BUILDKIT=1
          docker build --cache-from=type=gha --cache-to=type=gha,mode=max \
                       -t ghcr.io/stukenvitalii/taskmanager:latest \
                       -t ghcr.io/stukenvitalii/taskmanager:${{ github.sha }} .

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/stukenvitalii/taskmanager:latest
          docker push ghcr.io/stukenvitalii/taskmanager:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          docker tag ghcr.io/stukenvitalii/taskmanager:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/taskmanager:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/taskmanager:latest
